# Generated by Django 4.2.10 on 2025-10-11 22:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LegalPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('page_type', models.CharField(choices=[('privacy', 'Privacy Policy'), ('terms', 'Terms of Service'), ('cookie', 'Cookie Policy'), ('disclaimer', 'Disclaimer'), ('refund', 'Refund Policy'), ('dmca', 'DMCA Policy')], max_length=20, unique=True)),
                ('content', models.TextField(help_text='Full legal content')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('effective_date', models.DateField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('meta_title', models.CharField(blank=True, help_text='SEO title', max_length=60)),
                ('meta_description', models.CharField(blank=True, help_text='SEO description', max_length=160)),
                ('meta_keywords', models.CharField(blank=True, help_text='SEO keywords', max_length=255)),
            ],
            options={
                'verbose_name': 'Legal Page',
                'verbose_name_plural': 'Legal Pages',
                'ordering': ['page_type'],
            },
        ),
        migrations.CreateModel(
            name='SEOSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='DeeValley', max_length=100)),
                ('site_description', models.CharField(default="Kenya's premier real estate platform", max_length=160)),
                ('site_keywords', models.TextField(default='real estate Kenya, property Kenya, homes for sale, apartments for rent')),
                ('facebook_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('phone', models.CharField(default='+254 797 398004', max_length=20)),
                ('email', models.EmailField(default='vincentotienoakuku@gmail.com', max_length=254)),
                ('address', models.CharField(default='Nairobi, Kenya', max_length=200)),
                ('google_analytics_id', models.CharField(blank=True, help_text='GA4 Measurement ID', max_length=20)),
                ('google_tag_manager_id', models.CharField(blank=True, help_text='GTM Container ID', max_length=20)),
                ('facebook_pixel_id', models.CharField(blank=True, max_length=20)),
                ('organization_logo', models.ImageField(blank=True, upload_to='seo/')),
                ('default_image', models.ImageField(blank=True, help_text='Default OG image', upload_to='seo/')),
            ],
            options={
                'verbose_name': 'SEO Settings',
                'verbose_name_plural': 'SEO Settings',
            },
        ),
        migrations.CreateModel(
            name='Sitemap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('priority', models.DecimalField(decimal_places=1, default=0.5, max_digits=2)),
                ('changefreq', models.CharField(choices=[('always', 'Always'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('never', 'Never')], default='weekly', max_length=10)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-priority', 'url'],
            },
        ),
    ]
