# Generated by Django 5.2.1 on 2025-10-20 08:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0007_auto_20251013_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagedProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('management_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending'), ('completed', 'Completed')], default='active', help_text='Current management status of the property', max_length=20)),
                ('management_start_date', models.DateField(default=django.utils.timezone.now)),
                ('management_end_date', models.DateField(blank=True, null=True)),
                ('management_notes', models.TextField(blank=True, help_text='Internal notes about property management')),
                ('maintenance_required', models.BooleanField(default=False)),
                ('maintenance_notes', models.TextField(blank=True, help_text='Maintenance requirements or issues')),
                ('occupancy_status', models.CharField(choices=[('occupied', 'Occupied'), ('vacant', 'Vacant'), ('under_maintenance', 'Under Maintenance')], default='vacant', max_length=20)),
                ('last_inspection_date', models.DateField(blank=True, null=True)),
                ('next_inspection_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='managed_property', to='listings.listing')),
            ],
            options={
                'verbose_name': 'Managed Property',
                'verbose_name_plural': 'Managed Properties',
                'ordering': ['-management_start_date'],
            },
        ),
    ]
