# Generated by Django 4.2.10 on 2025-10-08 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='client_email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='client_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
