# Generated by Django 4.2.10 on 2025-10-11 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_alter_booking_unique_together_booking_check_in_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='check_in_time',
            field=models.TimeField(blank=True, default='15:00', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='check_out_time',
            field=models.TimeField(blank=True, default='11:00', null=True),
        ),
    ]
