# Generated by Django 4.2.10 on 2025-10-13 12:58

from django.db import migrations
import uuid

def gen_uuid(apps, schema_editor):
    ListingSubscription = apps.get_model("listings", "ListingSubscription")
    for row in ListingSubscription.objects.all():
        row.unsubscribe_token = uuid.uuid4()
        row.save(update_fields=["unsubscribe_token"])

class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_listingsubscription'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
