# Generated by Django 4.2.10 on 2025-10-13 12:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_auto_20251013_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingsubscription',
            name='unsubscribe_token',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
