# Generated by Django 4.2.10 on 2025-10-11 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('short_description', models.CharField(help_text='Brief description for cards and footer', max_length=300)),
                ('description', models.TextField(help_text='Full description for service detail page')),
                ('icon_class', models.CharField(default='fas fa-home', help_text='FontAwesome icon class (e.g., fas fa-home)', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/%Y/%m/%d/')),
                ('is_featured', models.BooleanField(default=False, help_text='Show in footer and homepage')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, help_text='SEO title (leave blank to use title)', max_length=60)),
                ('meta_description', models.CharField(blank=True, help_text='SEO description', max_length=160)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['order', 'title'],
            },
        ),
    ]
