# Generated by Django 5.2.1 on 2025-10-16 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='meta_description',
            field=models.CharField(blank=True, help_text='SEO description', max_length=300),
        ),
    ]
