# Generated by Django 4.2.10 on 2025-10-13 13:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogsubscription',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='blogsubscription',
            name='unsubscribe_token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
    ]
