# Generated by Django 4.2.10 on 2025-10-13 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogsubscription_is_active_and_more'),
    ]

    operations = [
    ]
