# Generated by Django 4.2.10 on 2025-10-13 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20251013_1601'),
        ('blog', '0003_populate_uuid_values'),
    ]

    operations = [
    ]
