# Generated by Django 4.2.10 on 2025-10-13 13:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_merge_20251013_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogsubscription',
            name='unsubscribe_token',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
