# Generated by Django 5.2.1 on 2026-06-21 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='realtor',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Only admins can verify realtors. Verified realtors can have published listings.'),
        ),
        migrations.AddField(
            model_name='realtor',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='realtor',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_realtors', to=settings.AUTH_USER_MODEL),
        ),
    ]
