bedroom_choices = {
    '1': 1,
    '2': 2,
    '3': 3,
    '4': 4,
    '5': 5,
    '6': 6,
    '7': 7,
    '8': 8,
    '9': 9,
    '10': 10
}

price_choices = {
    '1000': 'KSh 1,000 - 5,000 / $7 - $35',
    '5000': 'KSh 5,000 - 10,000 / $35 - $70',
    '10000': 'KSh 10,000 - 15,000 / $70 - $105',
    '15000': 'KSh 15,000 - 20,000 / $105 - $140',
    '20000': 'KSh 20,000 - 30,000 / $140 - $210',
    '30000': 'KSh 30,000 - 50,000 / $210 - $350',
    '50000': 'KSh 50,000 - 100,000 / $350 - $700',
    '100000': 'KSh 100,000 - 200,000 / $700 - $1,400',
    '200000': 'KSh 200,000 - 500,000 / $1,400 - $3,500',
    '500000': 'KSh 500,000 - 1,000,000 / $3,500 - $7,000',
    '1000000': 'KSh 1,000,000+ / $7,000+',
}

state_choices = {

    'BAR': 'Baringo',
    'BOM': 'Bomet',
    'BUN': 'Bungoma',
    'BUS': 'Busia',
    'ELG': 'Elgeyo-Marakwet',
    'EMB': 'Embu',
    'GAR': 'Garissa',
    'HOM': 'Homa Bay',
    'ISI': 'Isiolo',
    'KAJ': 'Kajiado',
    'KAK': 'Kakamega',
    'KAM': 'Kericho',
    'KIL': 'Kilifi',
    'KIR': 'Kirinyaga',
    'KIS': 'Kisii',
    'KIT': 'Kitui',
    'KWA': 'Kwale',
    'LAI': 'Laikipia',
    'LAM': 'Lamu',
    'MAC': 'Machakos',
    'MAK': 'Makueni',
    'MAN': 'Mandera',
    'MAR': 'Marsabit',
    'MER': 'Meru',
    'MIG': 'Migori',
    'MOM': 'Mombasa',
    'MUR': 'Murang\'a',
    'NAI': 'Nairobi',
    'NAK': 'Nakuru',
    'NAN': 'Nandi',
    'NAR': 'Narok',
    'NYA': 'Nyamira',
    'NAN': 'Nyandarua',
    'NYE': 'Nyeri',
    'SAM': 'Samburu',
    'SIA': 'Siaya',
    'TAI': 'Taita-Taveta',
    'TAN': 'Tana River',
    'THA': 'Tharaka-Nithi',
    'TRA': 'Trans Nzoia',
    'TUR': 'Turkana',
    'UAS': 'Uasin Gishu',
    'VIH': 'Vihiga',
    'WAJ': 'Wajir',
    'WES': 'West Pokot',
    'DZ': 'Algeria',
    'AO': 'Angola',
    'BJ': 'Benin',
    'BW': 'Botswana',
    'BF': 'Burkina Faso',
    'BI': 'Burundi',
    'CV': 'Cape Verde',
    'CM': 'Cameroon',
    'CF': 'Central African Republic',
    'TD': 'Chad',
    'KM': 'Comoros',
    'CG': 'Congo',
    'CD': 'Democratic Republic of Congo',
    'CI': 'Côte d\'Ivoire',
    'DJ': 'Djibouti',
    'EG': 'Egypt',
    'GQ': 'Equatorial Guinea',
    'ER': 'Eritrea',
    'SZ': 'Eswatini',
    'ET': 'Ethiopia',
    'GA': 'Gabon',
    'GM': 'Gambia',
    'GH': 'Ghana',
    'GN': 'Guinea',
    'GW': 'Guinea-Bissau',
    'KE': 'Kenya',
    'LS': 'Lesotho',
    'LR': 'Liberia',
    'LY': 'Libya',
    'MG': 'Madagascar',
    'MW': 'Malawi',
    'ML': 'Mali',
    'MR': 'Mauritania',
    'MU': 'Mauritius',
    'MA': 'Morocco',
    'MZ': 'Mozambique',
    'NA': 'Namibia',
    'NE': 'Niger',
    'NG': 'Nigeria',
    'RW': 'Rwanda',
    'ST': 'São Tomé and Príncipe',
    'SN': 'Senegal',
    'SC': 'Seychelles',
    'SL': 'Sierra Leone',
    'SO': 'Somalia',
    'ZA': 'South Africa',
    'SS': 'South Sudan',
    'SD': 'Sudan',
    'TZ': 'Tanzania',
    'TG': 'Togo',
    'TN': 'Tunisia',
    'UG': 'Uganda',
    'ZM': 'Zambia',
    'ZW': 'Zimbabwe'
}
