bedroom_choices = {
    '1': 1,
    '2': 2,
    '3': 3,
    '4': 4,
    '5': 5,
    '6': 6,
    '7': 7,
    '8': 8,
    '9': 9,
    '10': 10
}

price_choices = {
    '1000': '1,000',
    '5000': '5,000',
    '10000': '10,000',
    '25000': '25,000',
    '50000': '50,000',
    '100000': '100,000',
    '250000': '250,000',
    '500000': '500,000',
    '1000000': '1M',
    '2500000': '2.5M',
    '5000000': '5M',
    '10000000': '10M',
    '25000000': '25M',
    '50000000': '50M',
    '100000000': '100M',
    '250000000': '250M',
    '500000000': '500M',
    '1000000000': '1B+',
}

state_choices = {

    'BAR': 'Baringo',
    'BOM': 'Bomet',
    'BUN': 'Bungoma',
    'BUS': 'Busia',
    'ELG': 'Elgeyo-Marakwet',
    'EMB': 'Embu',
    'GAR': 'Garissa',
    'HOM': 'Homa Bay',
    'ISI': 'Isiolo',
    'KAJ': 'Kajiado',
    'KAK': 'Kakamega',
    'KAM': 'Kericho',
    'KIL': 'Kilifi',
    'KIR': 'Kirinyaga',
    'KIS': 'Kisii',
    'KIT': 'Kitui',
    'KWA': 'Kwale',
    'LAI': 'Laikipia',
    'LAM': 'Lamu',
    'MAC': 'Machakos',
    'MAK': 'Makueni',
    'MAN': 'Mandera',
    'MAR': 'Marsabit',
    'MER': 'Meru',
    'MIG': 'Migori',
    'MOM': 'Mombasa',
    'MUR': 'Murang\'a',
    'NAI': 'Nairobi',
    'NAK': 'Nakuru',
    'NAN': 'Nandi',
    'NAR': 'Narok',
    'NYA': 'Nyamira',
    'NAN': 'Nyandarua',
    'NYE': 'Nyeri',
    'SAM': 'Samburu',
    'SIA': 'Siaya',
    'TAI': 'Taita-Taveta',
    'TAN': 'Tana River',
    'THA': 'Tharaka-Nithi',
    'TRA': 'Trans Nzoia',
    'TUR': 'Turkana',
    'UAS': 'Uasin Gishu',
    'VIH': 'Vihiga',
    'WAJ': 'Wajir',
    'WES': 'West Pokot',
    'DZ': 'Algeria',
    'AO': 'Angola',
    'BJ': 'Benin',
    'BW': 'Botswana',
    'BF': 'Burkina Faso',
    'BI': 'Burundi',
    'CV': 'Cape Verde',
    'CM': 'Cameroon',
    'CF': 'Central African Republic',
    'TD': 'Chad',
    'KM': 'Comoros',
    'CG': 'Congo',
    'CD': 'Democratic Republic of Congo',
    'CI': 'Côte d\'Ivoire',
    'DJ': 'Djibouti',
    'EG': 'Egypt',
    'GQ': 'Equatorial Guinea',
    'ER': 'Eritrea',
    'SZ': 'Eswatini',
    'ET': 'Ethiopia',
    'GA': 'Gabon',
    'GM': 'Gambia',
    'GH': 'Ghana',
    'GN': 'Guinea',
    'GW': 'Guinea-Bissau',
    'KE': 'Kenya',
    'LS': 'Lesotho',
    'LR': 'Liberia',
    'LY': 'Libya',
    'MG': 'Madagascar',
    'MW': 'Malawi',
    'ML': 'Mali',
    'MR': 'Mauritania',
    'MU': 'Mauritius',
    'MA': 'Morocco',
    'MZ': 'Mozambique',
    'NA': 'Namibia',
    'NE': 'Niger',
    'NG': 'Nigeria',
    'RW': 'Rwanda',
    'ST': 'São Tomé and Príncipe',
    'SN': 'Senegal',
    'SC': 'Seychelles',
    'SL': 'Sierra Leone',
    'SO': 'Somalia',
    'ZA': 'South Africa',
    'SS': 'South Sudan',
    'SD': 'Sudan',
    'TZ': 'Tanzania',
    'TG': 'Togo',
    'TN': 'Tunisia',
    'UG': 'Uganda',
    'ZM': 'Zambia',
    'ZW': 'Zimbabwe'
}
